---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: dryrun
    image: thegeeklab/drone-docker-buildx:20
    settings:
      dockerfile: Dockerfile
      dry_run: true
      platforms:
        - linux/amd64
      repo: xoxys/${DRONE_REPO_NAME}

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
